### PR TITLE
Topic/gcc9 support

### PR DESCRIPTION
**Pull request by sodero**
Experimental gcc 9 support.

### CODE REVIEW

**Comment by sba1** [comment]
Thanks for your contribution. Do you have an idea, why the disablement für C++17 is necessary? It would be nice to document in the patch as it can be possibily fixed easier that way.

**Comment by sodero** [comment]
I'm afraid I don't know so I wrote nothing about it (better to be silent than to lie I guess). It's about clib2 though. To be very specific there are things that aren't exposed in the std namespace due to the following in libstdc++-v3/include/c_global/cstddef and c_std/cstddef. It says that c++11 doesn't work either but at least it builds with it enabled. I haven't tried to build any c++ code though. I have tried to build MUI-Vim (which is c-only) and that works. ScummVM works as well I've been told.

extern "C++"
{
#if __cplusplus >= 201103L
namespace std
{
/* Needed as clib2 on AmigaOS has no C11 support yet */
#if __STDC_VERSION__ >= 201112L
  // We handle size_t, ptrdiff_t, and nullptr_t in c++config.h.
  using ::max_align_t;
#endif
}
#endif // C++11

**Comment by sba1** [comment]
Am 2021-01-02 23:02, schrieb Ola Söder:
> I'm afraid I don't know so I wrote nothing about it (better to be
> silent than to lie I guess). It's about clib2 though. To be very
> specific there are things that aren't exposed in the std namespace due
> to the following in libstdc++-v3/include/c_global/cstddef and
> c_std/cstddef. It says that c++11 doesn't work either but at least it
> builds with it enabled. I haven't tried to build any c++ code though.

It would be nice if you could add this to the patch description (at 
least that the disablement is clib2 related). There are definitively 
problems with clib2 but also with newlib. The former is OpenSource and 
could possibly be fixed by someone.

Bye
Sebastian

**Comment by sodero** [comment]
I'll fix that.

**Comment by raziel-** [comment]
ScummVM switched to using c++11 functions a few months back, but they also use fallback if c++11 isn't supported.

So, I can't really confirm that they are used, but I guess they di, because there was no information about it falling back during configure

**Comment by sodero** [comment]
Interesting. That's good news, but I don't understand why it works :) (if it really does)

**Comment by sodero** [comment]
I updated the 'disable c++17' commit with some more info.

**Comment by sba1** [comment]
Thanks, I merged your changes!

**Pull request merged**
