### PR TITLE
GCC 10.3.0 support.

### PR DESCRIPTION
**Pull request by sodero**
Two patches haven't been applied. At least one of them is 68k specific
and can't be applied due to changes in the upstream 68k support. Refer
to patch 0028 and line 201 and 210 in patch 0025.

### CODE REVIEW

**Comment by sba1** [comment]
I looked through the patch. Can you please file some Issues for things that are not solved yet? Such as the tagtype and 68k support. I also suggest more elaboration of the fs implementation with respect to the unix path compatibility layer. I'm not sure if the changes are necessary in case this layer is used.

That way it is clear what remains to be done and we can mark the 10.3.0 as a kind of prerelease.

**Comment by sodero** [comment]
I'll fix that.

**Comment by sba1** [comment]
> As far as the fs compatibility layer is concerned: I haven't looked deeply into this but if I understand correctly this is about interpreting strings. Those strings might be Amiga user input so then we need to cater for things like ':', '/' and so on.

Yes, it can be user input but as the path semantics are not complementary, the user input must be a Unix style path if the compatibility layer is enabled. As the remaining of the patch is more important in my opinion, I'll merge it anyway and we need to think about the problem later. Thanks for your hard work!

**Comment by sodero** [comment]
No problem. You did all the hard work here. It's a nice way of managing patches.

**Pull request merged**
