### PR TITLE
Updated the readme document

### PR DESCRIPTION
**Pull request by 3246251196**
Update ReadMe file with packages that are missing from current ReadMe.

Remove outdated references to BIN packages that are no longer maintained.

### CODE REVIEW

**Comment by sba1** [comment]
There is a lot of text removed. Could you explain this a little bit?

**Comment by 3246251196** [comment]
@sba1 
- The travis server no longer exists,
- No one is maintaining apt packages anymore and the links do not exist,
- The large text is to do with the installation of the deb package which does not exist,
- Previously, the section talked about some requisite libraries, but it was not exhaustive enough. It should also include bison and flex; it was common - a while ago - for me to start from a fresh machine, read the README, install those packages and wonder why I was still getting an error during building; it was because BISON was missing.
- The section about which LHA tool to use is also vital. LHASA is simply not good enough.

**Comment by sba1** [comment]
I would rather like to see that this feature for building the distribution is reimplemented than removed entirely. Maybe you can reduce your changes to a minimum. The mentioning of bison is definitively helpful as the removal of the non-working badges is.

**Comment by 3246251196** [comment]
@sba1 
Okay. I wonder who will maintain a debian package though. No one seems to be doing it right now. The alternative would be to upload RELEASEs on this repository containing a final LHA.

**Comment by 3246251196** [comment]
@sba1 
Are you still not interested in pulling this change? I won't be hosting built packages and I do not think you will be either. No one else is holding their hands up either.

Does it not make sense to accept this PR?

**Comment by sba1** [comment]
I plan myself to reactivate the build

**Comment by 3246251196** [comment]
Then, let me close this PR and make another one for some document changes.

**Pull request closed without merging**
